### ISSUE TITLE
Invisible Keys on CMD / Cmder / Powershell - on Windows

### ISSUE THREAD

**Issue by thiagoloureiro** [lirantal/dockly#52]
## Expected Behavior
Show keys

## Actual Behavior
![image](https://user-images.githubusercontent.com/29433794/38770402-f8413f0e-4012-11e8-9941-bec6977ed500.png)

## Steps to Re-produce the Problem

  1. Install dockly

  2. Open Dockly

  3. Missing Keys from Menus

## Context

- Operating System:
- Node.js version (run `node --version`): v8.9.4
- Package version: 3.3.1
- Docker version (run `docker --version`): Docker version 18.03.0-ce, build 0520e24
- Is docker installed locally? Yes
- Do you have containers created? Yes
- Does this file exists `/var/run/docker.sock` ? n/a
- Output of `docker info`:

**Comment by lirantal** [comment]
@thiagoloureiro hey!
so you aren't seeing the shortcuts since they appear to be black, right?

**Comment by thiagoloureiro** [comment]
@lirantal  exactly, only when I guess the shortcut he appear because have focus, but I Don't know what is the others because it's all black. (try

**Comment by lirantal** [comment]
good point. choosing white will be a bit confusing due to the text being white too.
how does yellow look like?

![image](https://user-images.githubusercontent.com/316371/38771136-34115074-4026-11e8-806c-31c77d47bcc9.png)

![image](https://user-images.githubusercontent.com/316371/38771142-3f8a8c7c-4026-11e8-9cf5-5a932e2725f3.png)

![image](https://user-images.githubusercontent.com/316371/38771146-4ea6540c-4026-11e8-8d3f-84b76e31921d.png)

**Comment by thiagoloureiro** [comment]
Yellow looks nice 👍

**Comment by lirantal** [comment]
Cool, give me a sec to push in the change and you'll have a new version available in a couple of minutes.

**Comment by lirantal** [comment]
3.3.2 released
can you test?

**Comment by thiagoloureiro** [comment]
@lirantal  working , thanks a million.

**Comment by lirantal** [comment]
my pleasure ;-)
