### ISSUE TITLE
Error when container not running?

### ISSUE THREAD

**Issue by cjus** [lirantal/dockly#7]
I tried running dockly and received the following error.  After running a container (redis) dockly seem to work just fine.

```
Error: Unable to determine the domain name
-> check your connection options to the docker daemon and confirm containers exist
```

**Comment by lirantal** [comment]
thanks @cjus 
so basically if there aren't any running containers it doesn't load, right?
it makes sense a bit because it also only displays running containers in the list.

I'll be very happy to get some input and feedback on things to improve

**Comment by cjus** [comment]
@lirantal yes that's right.

**Comment by lirantal** [comment]
@cjus It should be fixed too and will definitely have  all containers listed, even those that are exited.

I'd love to ask you for some UI feedback, you're using the npm version right?
I changed the UI a bit in the repo's master branch but I'm not feeling it connects yet. Currently in my latest changes branch it looks like this:

![image](https://cloud.githubusercontent.com/assets/316371/22713200/1be2e9de-ed90-11e6-918e-04e87399297d.png)

I originally did the change because I wanted to make more width space for the logs but not sure it's a better UI representation.

**Comment by lirantal** [comment]
Fixed
