### ISSUE TITLE
Scroll through logs?

### ISSUE THREAD

**Issue by davidlivingrooms** [lirantal/dockly#78]
Hi, this tool is already so great. Thanks for your hard work! 

This may already be possible so please feel free to close if so. Is it possible to scroll through the entire logs for a container? The view window is rather small and seems to be truncated by default which makes sense for the dashboard. However, having an option to view the full logs somehow would make this my number 1 docker tool. 

We could have a button at the bottom that opens the full logs in a model similar to `info`. Maybe it happens automatically if you press return twice quickly?

**Comment by lirantal** [comment]
Thanks for the kind words 😊 

That's a great idea!
I was thinking we can have a `+` key binding that whether you are viewing the containers list or the logs it will expand them to full screen. We don't need to open it as a new widget, just to re-layout the screen so that they take up the whole space.

WDYT?
Also, specifically using the `+` key you'd need to have 2 keystrokes (shift and `=`) because `=` is already bound to refresh the containers list. Maybe we can use `-` instead if the 2 keystrokes are too much.

**Comment by chasingSublimity** [comment]
Hey there! I'm happy to take a swing at this issue. I'm still poking around the source code and may have some questions, but I think I can get something submitted for review here soon. :)

**Comment by lirantal** [comment]
Sounds great! I'm here to help, so don't hesitate to ask.

**Comment by KadenLNelson** [comment]
> Sounds great! I'm here to help, so don't hesitate to ask.

I have a couple of questions, do you have any communication platforms? Slack, Keybase, etc..

**Comment by lirantal** [comment]
I guess here would be just fine...? 
Otherwise I'm on twitter tool, you can DM me there if needed (`@liran_tal`)
