### ISSUE TITLE
Feature request: start shell in same terminal window

### ISSUE THREAD

**Issue by daanbeverdam** [lirantal/dockly#83]
Right now when starting a shell for a docker container, the `dockerRunScript.sh` is launched in a new tab/window. Is it possible to have this script open in the same window (possibly integrated within the Dockly interface)? If you could give me some pointers on how to do this, I'll be more than happy to make a pull request.

**Comment by lirantal** [comment]
@daanbeverdam thanks for chiming in and happy to hear dockly is helpful for you.

To make that happen it will require to current running shell command (dockly itself) to terminate and spawn a new command to connect to the container on the same shell. Upon exiting the command it will re-spawn dockly so you can go back and continue. Could work but sounds a bit qwarky no?

Another option is to embed an actuall shell through JS inside the dockly interface but sounds like a ton of work and not really worth it in terms of the effort, maintenance and dependencies it will require.

Happy to hear more thoughts on this though.

**Comment by daanbeverdam** [comment]
Thanks for your reply (and sorry for my late one)! True, the embedded shell sounds like too much effort for a feature this small. For me, it would be fine to 'lose' the Dockly instance and not have it come back up after I exit the container's shell. Doesn't feel more hacky to me than opening it in a new tab, but our opinions may differ on that.

Would you consider merging if I'd implement it that way?

**Comment by lirantal** [comment]
I love the pro-activeness spirit!

I'm happy to merge it if you can make it happen.
Would like to think however how would we call it (i.e shortcuts system today) and thinking maybe it can be a config flag (say an environment variable) where the default is to keep existing functionality as is today?

**Comment by daanbeverdam** [comment]
Great! Yeah, seems like a good idea. I'll look into it when I can find the time and keep you posted!

**Comment by lirantal** [comment]
Sounds great!

**Comment by triforcely** [comment]
Hey! I created [PoC for this feature](https://github.com/triforcely/dockly/commit/c7381bf41d15b75f46ca8d203de175dec5a63bff)

![integrated-shell](https://user-images.githubusercontent.com/12202969/52742747-bead9880-2fd8-11e9-84b0-55d339f4c7e8.gif)

It basically freezes blessedjs (because of execSync), clears console and executes docker command. After interactive console is exitted, console is cleared and blessedjs is forced to redraw whole screen - blessedjs keeps track of changes but my _stdio magic_ causes it to get out of sync. Standard streams are seamlessly inheritted, so it should theoretically work in any shell and OS - even through SSH. Application is never closed, so application state is untouched. Also, there is no need for separate *.sh script (or Windows equivalent)

It works fine on Windows 10 and mostly on ubuntu but I'm unable to run docker inside docker (😅), so some help with testing would be appreciated!

Could you help me with testing if it works on linux?

**Comment by lirantal** [comment]
Woah great job @triforcely! 🔥
I can help test it on Mac, Linux and inside a docker container.

**Comment by lirantal** [comment]
Fixed by #97
