### ISSUE TITLE
Is it possible to add package-lock.json to the gitignore?

### ISSUE THREAD

**Issue by KadenLNelson** [lirantal/dockly#89]
I browsed the repositories history for a while, I noticed that `package-lock.json` hasn't been in the repo's tracked files. Is it possible to add to `.gitignore` to reduce noise?

**Comment by lirantal** [comment]
For developing on dockly I use yarn instead of npm, so that's why you don't see a `package-lock.json` and instead we have a `yarn.lock` on the repo:

![image](https://user-images.githubusercontent.com/316371/51424948-13c6dc00-1bde-11e9-8522-46b67e3c4960.png)

Sure, can you open a PR to update .gitignore?
